### ISSUE TITLE
nginx issue production

### ISSUE THREAD

**Issue by xfouloux** [guy0090/LostArkLogs#2]
Hi,

weird issue i guess with nginx, or vue ? but i don't know vue.

with production env :

when you go to the homepage it loads ok, no problem.
then you navigate to the logs page at : xxxx/logs via the left menu, it displays fine,
now you copy the url xxxx/logs, and type it in another browser tab and try to access it, 404 error.

it's particulary blocking for the login, as you are redirected to xxxx/login from another website, 404 error.

i'm blocked with this so far.

**Comment by xfouloux** [comment]
well for others that may have issues :

add a file in nginx folder named default.conf and paste this

```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

        #Vue router configuration
    location / {
                root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ @router;
        index index.html;
    }
    location @router {
        rewrite ^.*$ /index.html last;
    }

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```
then in docker-compose.yml in the `site` service add
```
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
```

if you got a nginx-proxy in front like me with jwilder/nginx-proxy you need to add to your vhost.d folder a file with the hotname of the frontend containing

```
    location @router {
        rewrite ^.*$ /index.html last;
    }
```

**Comment by guy0090** [comment]
This has to do with [Vue Router](https://router.vuejs.org/guide/essentials/history-mode.html#nginx), your solution does seem to fix it but I'll need to test it a bit before I push the commit.

Thanks!
