### ISSUE TITLE
Possibility of adding a "Me" tag to character played by uploader?

### ISSUE THREAD

**Issue by Celiken** [guy0090/LostArkLogs#6]
I'm not sure if it is possible to do with the way the logs works, but it would be pretty sweet to be able have your character tagged when going through your uploaded parses.
Maybe only visible when logged with the uploader account.

Something like this:
![image](https://user-images.githubusercontent.com/9248358/190648045-d5aae472-1ee5-4589-84eb-28b46e57de41.png)

**Comment by guy0090** [comment]
There's sadly no way to link characters to a user right now, which is why I held off on this. I could allow users to manually set one of the log participants to themselves but this would have to be manual.

**Comment by Celiken** [comment]
That's what I though.
Anyway, good work to you all who works on logger/details/lailai, insane job :)
